import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const root = process.cwd();
const includeRoots = [
  "00_Start_Here",
  "01_Main_Story",
  "02_Origins_and_Religion",
  "03_Taiping_State",
  "04_War_and_Campaigns",
  "05_Qing_Response",
  "06_Aftermath_and_Memory",
  "07_Reference",
  "08_Sources_and_Editing",
  "09_Backlog",
];

const sectionLabels = {
  "": "Home",
  "00_Start_Here": "Start Here",
  "01_Main_Story": "Main Story",
  "02_Origins_and_Religion": "Origins & Religion",
  "03_Taiping_State": "Taiping State",
  "04_War_and_Campaigns": "War & Campaigns",
  "05_Qing_Response": "Qing Response",
  "06_Aftermath_and_Memory": "Aftermath & Memory",
  "07_Reference": "Reference",
  "08_Sources_and_Editing": "Sources & Editing",
  "09_Backlog": "Backlog",
};

const order = ["index.md", "README.md"];

function walk(dir) {
  const entries = readdirSync(dir, { withFileTypes: true }).sort((a, b) =>
    a.name.localeCompare(b.name),
  );
  return entries.flatMap((entry) => {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) return walk(full);
    return entry.isFile() && entry.name.endsWith(".md") ? [full] : [];
  });
}

const files = [
  path.join(root, "index.md"),
  path.join(root, "README.md"),
  ...includeRoots.flatMap((dir) => walk(path.join(root, dir))),
];

function slugFromRelative(relative) {
  if (relative === "index.md") return "";
  return relative.replace(/\.md$/, "");
}

function titleFromMarkdown(markdown, relative) {
  const heading = markdown.match(/^#\s+(.+)$/m)?.[1]?.trim();
  return heading ?? path.basename(relative, ".md").replace(/[_-]/g, " ");
}

function excerptFromMarkdown(markdown) {
  const withoutTitle = markdown.replace(/^#\s+.+$/m, "").trim();
  const paragraph = withoutTitle
    .split(/\n{2,}/)
    .find((block) => /^[A-Za-z0-9*_\[]/.test(block.trim()));
  return (paragraph ?? "")
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
    .replace(/[*_`#>-]/g, "")
    .replace(/\s+/g, " ")
    .slice(0, 220)
    .trim();
}

function headingsFromMarkdown(markdown) {
  return [...markdown.matchAll(/^(#{2,3})\s+(.+)$/gm)].map((match) => ({
    level: match[1].length,
    text: match[2].replace(/[*_`]/g, "").trim(),
  }));
}

function readingMinutes(markdown) {
  const words = markdown.trim().split(/\s+/).filter(Boolean).length;
  return Math.max(1, Math.round(words / 230));
}

const pages = files.map((file) => {
  const relative = path.relative(root, file);
  const markdown = readFileSync(file, "utf8");
  const sectionKey = relative.includes(path.sep) ? relative.split(path.sep)[0] : "";
  return {
    slug: slugFromRelative(relative),
    sourcePath: relative,
    title: titleFromMarkdown(markdown, relative),
    section: sectionLabels[sectionKey] ?? "Wiki",
    markdown,
    excerpt: excerptFromMarkdown(markdown),
    headings: headingsFromMarkdown(markdown),
    readingMinutes: readingMinutes(markdown),
  };
});

pages.sort((a, b) => {
  const ai = order.indexOf(a.sourcePath);
  const bi = order.indexOf(b.sourcePath);
  if (ai !== -1 || bi !== -1) return (ai === -1 ? 99 : ai) - (bi === -1 ? 99 : bi);
  return a.sourcePath.localeCompare(b.sourcePath);
});

const sections = Object.values(
  pages.reduce((acc, page) => {
    acc[page.section] ??= { label: page.section, pages: [] };
    acc[page.section].pages.push({
      slug: page.slug,
      title: page.title,
      excerpt: page.excerpt,
      readingMinutes: page.readingMinutes,
    });
    return acc;
  }, {}),
);

const output = `/* This file is generated by scripts/generate-content.mjs. */\n\nexport type WikiHeading = { level: number; text: string };\nexport type WikiPage = {\n  slug: string;\n  sourcePath: string;\n  title: string;\n  section: string;\n  markdown: string;\n  excerpt: string;\n  headings: WikiHeading[];\n  readingMinutes: number;\n};\n\nexport const wikiPages = ${JSON.stringify(pages, null, 2)} satisfies WikiPage[];\n\nexport const wikiSections = ${JSON.stringify(sections, null, 2)};\n`;

writeFileSync(path.join(root, "app", "content.generated.ts"), output);
